### ISSUE TITLE
cannot init pandoc-include

### ISSUE THREAD

**Issue by PeterSommerlad** [alpianon/include-pandoc#3]
running inlcude-pandoc on macos with python 3.9 (installed via homebrew) creates the following error:

```
$ include-pandoc --update
updating pandoc wrapper... Traceback (most recent call last):
  File "/usr/local/bin/include-pandoc", line 51, in <module>
    create_addargs()
  File "/usr/local/lib/python3.9/site-packages/include_pandoc/createaddargs.py", line 35, in create_addargs
    version = " ".join(v.splitlines()[:2])
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by martinsramek** [comment]
I had the same issue. Solved it by installing python2, pip2 and then include-pandoc via pip2. include-pandoc is compatible with python2.x but not python 3.x.
